import { Component } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'app-view-girl',
  templateUrl: './view-girl.page.html',
  styleUrls: ['./view-girl.page.scss'],
})
export class ViewGirlPage {
  girl: string = '';
  girlSets = {
    // pinup: {
    //   text: [
    //     '../../assets/pinup/beachc.png',
    //     '../../assets/pinup/beach.png',
    //     '../../assets/pinup/clothesburst.png',
    //     '../../assets/pinup/festival.png',
    //     '../../assets/pinup/christmas.png',
    //     '../../assets/pinup/fireplace.png',
    //     '../../assets/pinup/anniversary.png',
    //     '../../assets/pinup/peppera.png',
    //     '../../assets/pinup/claudiaa.png',
    //     '../../assets/pinup/shibukia.png',
    //     '../../assets/pinup/bonichoco.png',
    //     '../../assets/pinup/marybellea.png',
    //     '../../assets/pinup/exploraa.png',
    //     '../../assets/pinup/ranmaa.png',
    //   ]
    // },
    // peanut: {
    //   text: [
    //     '../../assets/peanut/gallery-0.png',
    //     '../../assets/peanut/text-1.png',
    //     '../../assets/peanut/gallery-1.png',
    //     '../../assets/peanut/text-2.png',
    //     '../../assets/peanut/gallery-2a.png',
    //     '../../assets/peanut/gallery-2.png',
    //     '../../assets/peanut/text-3.png',
    //     '../../assets/peanut/gallery-3a.png',
    //     '../../assets/peanut/gallery-3.png',
    //     '../../assets/peanut/text-4.png',
    //     '../../assets/peanut/gallery-4a.png',
    //     '../../assets/peanut/gallery-4.png',
    //     '../../assets/peanut/text-5.png',
    //     '../../assets/peanut/gallery-5b.png',
    //     '../../assets/peanut/gallery-5a.png',
    //     '../../assets/peanut/gallery-5.png',
    //     '../../assets/peanut/text-6.png',
    //     '../../assets/peanut/gallery-6a.png',
    //     '../../assets/peanut/gallery-6.png',
    //     '../../assets/peanut/text-7.png',
    //     '../../assets/peanut/gallery-7.png',
    //     '../../assets/peanut/gallery-8.png',
    //   ],
    //   gallery: [
    //     '../../assets/peanut/gallery-0.png',
    //     '../../assets/peanut/gallery-1.png',
    //     '../../assets/peanut/gallery-2a.png',
    //     '../../assets/peanut/gallery-2.png',
    //     '../../assets/peanut/gallery-3a.png',
    //     '../../assets/peanut/gallery-3.png',
    //     '../../assets/peanut/gallery-4a.png',
    //     '../../assets/peanut/gallery-4.png',
    //     '../../assets/peanut/gallery-5b.png',
    //     '../../assets/peanut/gallery-5a.png',
    //     '../../assets/peanut/gallery-5.png',
    //     '../../assets/peanut/gallery-6a.png',
    //     '../../assets/peanut/gallery-6.png',
    //     '../../assets/peanut/gallery-7.png',
    //     '../../assets/peanut/gallery-8.png',
    //   ]
    // },
    // wendy: {
    //   text: [
    //     '../../assets/wendy/gallery-0.png',
    //     '../../assets/wendy/text-1.png',
    //     '../../assets/wendy/gallery-1.png',
    //     '../../assets/wendy/text-2.png',
    //     '../../assets/wendy/gallery-2a.png',
    //     '../../assets/wendy/gallery-2.png',
    //     '../../assets/wendy/text-3.png',
    //     '../../assets/wendy/gallery-3a.png',
    //     '../../assets/wendy/gallery-3.png',
    //     '../../assets/wendy/text-4.png',
    //     '../../assets/wendy/gallery-4a.png',
    //     '../../assets/wendy/gallery-4.png',
    //     '../../assets/wendy/text-5.png',
    //     '../../assets/wendy/gallery-5a.png',
    //     '../../assets/wendy/gallery-5.png',
    //     '../../assets/wendy/text-6.png',
    //     '../../assets/wendy/gallery-6a.png',
    //     '../../assets/wendy/gallery-6.png',
    //     '../../assets/wendy/text-7.png',
    //     '../../assets/wendy/gallery-7.png',
    //   ],
    //   gallery: [
    //     '../../assets/wendy/gallery-0.png',
    //     '../../assets/wendy/gallery-1.png',
    //     '../../assets/wendy/gallery-2a.png',
    //     '../../assets/wendy/gallery-2.png',
    //     '../../assets/wendy/gallery-3a.png',
    //     '../../assets/wendy/gallery-3.png',
    //     '../../assets/wendy/gallery-4a.png',
    //     '../../assets/wendy/gallery-4.png',
    //     '../../assets/wendy/gallery-5a.png',
    //     '../../assets/wendy/gallery-5.png',
    //     '../../assets/wendy/gallery-6a.png',
    //     '../../assets/wendy/gallery-6.png',
    //     '../../assets/wendy/gallery-7.png',
    //   ]
    // },
    // generica: {
    //   text: [
    //     '../../assets/generica/gallery-0.png',
    //     '../../assets/generica/text-1.png',
    //     '../../assets/generica/gallery-1.png',
    //     '../../assets/generica/text-2.png',
    //     '../../assets/generica/gallery-2a.png',
    //     '../../assets/generica/gallery-2.png',
    //     '../../assets/generica/text-3.png',
    //     '../../assets/generica/gallery-3a.png',
    //     '../../assets/generica/gallery-3.png',
    //     '../../assets/generica/text-4.png',
    //     '../../assets/generica/gallery-4a.png',
    //     '../../assets/generica/gallery-4.png',
    //     '../../assets/generica/text-5.png',
    //     '../../assets/generica/gallery-5a.png',
    //     '../../assets/generica/gallery-5.png',
    //     '../../assets/generica/text-6.png',
    //     '../../assets/generica/gallery-6a.png',
    //     '../../assets/generica/gallery-6.png',
    //     '../../assets/generica/text-7.png',
    //     '../../assets/generica/gallery-7.png',
    //   ],
    //   gallery: [
    //     '../../assets/generica/gallery-0.png',
    //     '../../assets/generica/gallery-1.png',
    //     '../../assets/generica/gallery-2a.png',
    //     '../../assets/generica/gallery-2.png',
    //     '../../assets/generica/gallery-3a.png',
    //     '../../assets/generica/gallery-3.png',
    //     '../../assets/generica/gallery-4a.png',
    //     '../../assets/generica/gallery-4.png',
    //     '../../assets/generica/gallery-5a.png',
    //     '../../assets/generica/gallery-5.png',
    //     '../../assets/generica/gallery-6a.png',
    //     '../../assets/generica/gallery-6.png',
    //     '../../assets/generica/gallery-7.png',
    //   ]
    // },
    // lotus: {
    //   text: [
    //     '../../assets/lotus/gallery-0.png',
    //     '../../assets/lotus/text-1.png',
    //     '../../assets/lotus/gallery-1.png',
    //     '../../assets/lotus/text-2.png',
    //     '../../assets/lotus/gallery-2.png',
    //     '../../assets/lotus/text-3.png',
    //     '../../assets/lotus/gallery-3a.png',
    //     '../../assets/lotus/gallery-3.png',
    //     '../../assets/lotus/text-4.png',
    //     '../../assets/lotus/gallery-4.png',
    //     '../../assets/lotus/text-5.png',
    //     '../../assets/lotus/gallery-5a.png',
    //     '../../assets/lotus/gallery-5.png',
    //     '../../assets/lotus/text-6.png',
    //     '../../assets/lotus/gallery-6.png',
    //     '../../assets/lotus/text-7.png',
    //     '../../assets/lotus/gallery-7.png',
    //   ],
    //   gallery: [
    //     '../../assets/lotus/gallery-0.png',
    //     '../../assets/lotus/gallery-1.png',
    //     '../../assets/lotus/gallery-2.png',
    //     '../../assets/lotus/gallery-3a.png',
    //     '../../assets/lotus/gallery-3.png',
    //     '../../assets/lotus/gallery-4.png',
    //     '../../assets/lotus/gallery-5a.png',
    //     '../../assets/lotus/gallery-5.png',
    //     '../../assets/lotus/gallery-6.png',
    //     '../../assets/lotus/gallery-7.png',
    //   ]
    // },
    // sofia: {
    //   text: [
    //     '../../assets/sofia/gallery-0.png',
    //     '../../assets/sofia/text-1.png',
    //     '../../assets/sofia/gallery-1.png',
    //     '../../assets/sofia/text-2.png',
    //     '../../assets/sofia/gallery-2a.png',
    //     '../../assets/sofia/gallery-2.png',
    //     '../../assets/sofia/text-3.png',
    //     '../../assets/sofia/gallery-3a.png',
    //     '../../assets/sofia/gallery-3.png',
    //     '../../assets/sofia/text-4.png',
    //     '../../assets/sofia/gallery-4a.png',
    //     '../../assets/sofia/gallery-4.png',
    //     '../../assets/sofia/text-5.png',
    //     '../../assets/sofia/gallery-5a.png',
    //     '../../assets/sofia/gallery-5.png',
    //     '../../assets/sofia/text-6.png',
    //     '../../assets/sofia/gallery-6a.png',
    //     '../../assets/sofia/gallery-6.png',
    //     '../../assets/sofia/text-7.png',
    //   ],
    //   gallery: [
    //     '../../assets/sofia/gallery-0.png',
    //     '../../assets/sofia/gallery-1.png',
    //     '../../assets/sofia/gallery-2a.png',
    //     '../../assets/sofia/gallery-2.png',
    //     '../../assets/sofia/gallery-3a.png',
    //     '../../assets/sofia/gallery-3.png',
    //     '../../assets/sofia/gallery-4a.png',
    //     '../../assets/sofia/gallery-4.png',
    //     '../../assets/sofia/gallery-5a.png',
    //     '../../assets/sofia/gallery-5.png',
    //     '../../assets/sofia/gallery-6a.png',
    //     '../../assets/sofia/gallery-6.png',
    //   ]
    // },
    // caitlin: {
    //   text: [
    //     '../../assets/caitlin/gallery-0.png',
    //     '../../assets/caitlin/text-1.png',
    //     '../../assets/caitlin/gallery-1.png',
    //     '../../assets/caitlin/text-2.png',
    //     '../../assets/caitlin/gallery-2a.png',
    //     '../../assets/caitlin/gallery-2.png',
    //     '../../assets/caitlin/text-3.png',
    //     '../../assets/caitlin/gallery-3.png',
    //     '../../assets/caitlin/text-4.png',
    //     '../../assets/caitlin/gallery-4a.png',
    //     '../../assets/caitlin/gallery-4.png',
    //     '../../assets/caitlin/text-5.png',
    //     '../../assets/caitlin/gallery-5.png',
    //     '../../assets/caitlin/text-6.png',
    //     '../../assets/caitlin/gallery-6.png',
    //     '../../assets/caitlin/text-7.png',
    //   ],
    //   gallery: [
    //     '../../assets/caitlin/gallery-0.png',
    //     '../../assets/caitlin/gallery-1.png',
    //     '../../assets/caitlin/gallery-2a.png',
    //     '../../assets/caitlin/gallery-2.png',
    //     '../../assets/caitlin/gallery-3.png',
    //     '../../assets/caitlin/gallery-4a.png',
    //     '../../assets/caitlin/gallery-4.png',
    //     '../../assets/caitlin/gallery-5.png',
    //     '../../assets/caitlin/gallery-6.png',
    //   ]
    // },
    // honey: {
    //   text: [
    //     '../../assets/honey/gallery-0.png',
    //     '../../assets/honey/text-4.png',
    //     '../../assets/honey/gallery-4a.png',
    //     '../../assets/honey/gallery-4.png',
    //     '../../assets/honey/text-5.png',
    //     '../../assets/honey/gallery-5a.png',
    //     '../../assets/honey/gallery-5.png',
    //     '../../assets/honey/text-6.png',
    //     '../../assets/honey/gallery-6a.png',
    //     '../../assets/honey/gallery-6.png',
    //     '../../assets/honey/text-7.png',
    //   ],
    //   gallery: [
    //     '../../assets/honey/gallery-0.png',
    //     '../../assets/honey/gallery-4a.png',
    //     '../../assets/honey/gallery-4.png',
    //     '../../assets/honey/gallery-5a.png',
    //     '../../assets/honey/gallery-5.png',
    //     '../../assets/honey/gallery-6a.png',
    //     '../../assets/honey/gallery-6.png',
    //   ]
    // },
    // sawyer: {
    //   text: [
    //     '../../assets/sawyer/gallery-0.png',
    //     '../../assets/sawyer/text-1.png',
    //     '../../assets/sawyer/gallery-1.png',
    //     '../../assets/sawyer/text-2.png',
    //     '../../assets/sawyer/gallery-2a.png',
    //     '../../assets/sawyer/gallery-2.png',
    //     '../../assets/sawyer/text-3.png',
    //     '../../assets/sawyer/gallery-3.png',
    //     '../../assets/sawyer/text-4.png',
    //     '../../assets/sawyer/gallery-4.png',
    //     '../../assets/sawyer/text-5.png',
    //     '../../assets/sawyer/gallery-5.png',
    //     '../../assets/sawyer/text-6.png',
    //     '../../assets/sawyer/gallery-6b.png',
    //     '../../assets/sawyer/gallery-6a.png',
    //     '../../assets/sawyer/gallery-6.png',
    //     '../../assets/sawyer/text-7.png',
    //     '../../assets/sawyer/gallery-7.png',
    //   ],
    //   gallery: [
    //     '../../assets/sawyer/gallery-0.png',
    //     '../../assets/sawyer/gallery-1.png',
    //     '../../assets/sawyer/gallery-2a.png',
    //     '../../assets/sawyer/gallery-2.png',
    //     '../../assets/sawyer/gallery-3.png',
    //     '../../assets/sawyer/gallery-4.png',
    //     '../../assets/sawyer/gallery-5.png',
    //     '../../assets/sawyer/gallery-6b.png',
    //     '../../assets/sawyer/gallery-6a.png',
    //     '../../assets/sawyer/gallery-6.png',
    //     '../../assets/sawyer/gallery-7.png',
    //   ]
    // },
    // lake: {
    //   text: [
    //     '../../assets/lake/gallery-0.png',
    //     '../../assets/lake/text-1.png',
    //     '../../assets/lake/gallery-1.png',
    //     '../../assets/lake/text-2.png',
    //     '../../assets/lake/gallery-2a.png',
    //     '../../assets/lake/gallery-2.png',
    //     '../../assets/lake/text-3.png',
    //     '../../assets/lake/gallery-3a.png',
    //     '../../assets/lake/gallery-3.png',
    //     '../../assets/lake/text-4.png',
    //     '../../assets/lake/gallery-4a.png',
    //     '../../assets/lake/gallery-4.png',
    //     '../../assets/lake/text-5.png',
    //     '../../assets/lake/gallery-5a.png',
    //     '../../assets/lake/gallery-5.png',
    //     '../../assets/lake/text-6.png',
    //     '../../assets/lake/gallery-6b.png',
    //     '../../assets/lake/gallery-6a.png',
    //     '../../assets/lake/gallery-6.png',
    //     '../../assets/lake/text-7.png',
    //     '../../assets/lake/gallery-7.png',
    //   ],
    //   gallery: [
    //     '../../assets/lake/gallery-0.png',
    //     '../../assets/lake/gallery-1.png',
    //     '../../assets/lake/gallery-2a.png',
    //     '../../assets/lake/gallery-2.png',
    //     '../../assets/lake/gallery-3a.png',
    //     '../../assets/lake/gallery-3.png',
    //     '../../assets/lake/gallery-4a.png',
    //     '../../assets/lake/gallery-4.png',
    //     '../../assets/lake/gallery-5a.png',
    //     '../../assets/lake/gallery-5.png',
    //     '../../assets/lake/gallery-6b.png',
    //     '../../assets/lake/gallery-6a.png',
    //     '../../assets/lake/gallery-6.png',
    //     '../../assets/lake/gallery-7.png',
    //   ]
    // },
    // willow: {
    //   text: [
    //     '../../assets/willow/gallery-0.png',
    //     '../../assets/willow/text-1.png',
    //     '../../assets/willow/gallery-1.png',
    //     '../../assets/willow/text-2.png',
    //     '../../assets/willow/gallery-2a.png',
    //     '../../assets/willow/gallery-2.png',
    //     '../../assets/willow/text-3.png',
    //     '../../assets/willow/gallery-3a.png',
    //     '../../assets/willow/gallery-3.png',
    //     '../../assets/willow/text-4.png',
    //     '../../assets/willow/gallery-4a.png',
    //     '../../assets/willow/gallery-4.png',
    //     '../../assets/willow/text-5.png',
    //     '../../assets/willow/gallery-5a.png',
    //     '../../assets/willow/gallery-5.png',
    //     '../../assets/willow/text-6.png',
    //     '../../assets/willow/gallery-6a.png',
    //     '../../assets/willow/gallery-6.png',
    //     '../../assets/willow/text-7.png',
    //   ],
    //   gallery: [
    //     '../../assets/willow/gallery-0.png',
    //     '../../assets/willow/gallery-1.png',
    //     '../../assets/willow/gallery-2a.png',
    //     '../../assets/willow/gallery-2.png',
    //     '../../assets/willow/gallery-3a.png',
    //     '../../assets/willow/gallery-3.png',
    //     '../../assets/willow/gallery-4a.png',
    //     '../../assets/willow/gallery-4.png',
    //     '../../assets/willow/gallery-5a.png',
    //     '../../assets/willow/gallery-5.png',
    //     '../../assets/willow/gallery-6a.png',
    //     '../../assets/willow/gallery-6.png',
    //   ]
    // },
    // blanche: {
    //   text: [
    //     '../../assets/blanche/gallery-0.png',
    //     '../../assets/blanche/text-1.png',
    //     '../../assets/blanche/gallery-1.png',
    //     '../../assets/blanche/text-2.png',
    //     '../../assets/blanche/gallery-2a.png',
    //     '../../assets/blanche/gallery-2.png',
    //     '../../assets/blanche/text-3.png',
    //     '../../assets/blanche/gallery-3a.png',
    //     '../../assets/blanche/gallery-3.png',
    //     '../../assets/blanche/text-4.png',
    //     '../../assets/blanche/gallery-4a.png',
    //     '../../assets/blanche/gallery-4.png',
    //     '../../assets/blanche/text-5.png',
    //     '../../assets/blanche/gallery-5a.png',
    //     '../../assets/blanche/gallery-5.png',
    //     '../../assets/blanche/text-6.png',
    //     '../../assets/blanche/gallery-6a.png',
    //     '../../assets/blanche/gallery-6.png',
    //     '../../assets/blanche/text-7.png',
    //   ],
    //   gallery: [
    //     '../../assets/blanche/gallery-0.png',
    //     '../../assets/blanche/gallery-1.png',
    //     '../../assets/blanche/gallery-2a.png',
    //     '../../assets/blanche/gallery-2.png',
    //     '../../assets/blanche/gallery-3a.png',
    //     '../../assets/blanche/gallery-3.png',
    //     '../../assets/blanche/gallery-4a.png',
    //     '../../assets/blanche/gallery-4.png',
    //     '../../assets/blanche/gallery-5a.png',
    //     '../../assets/blanche/gallery-5.png',
    //     '../../assets/blanche/gallery-6a.png',
    //     '../../assets/blanche/gallery-6.png',
    //   ]
    // },
    // babybelle: {
    //   text: [
    //     '../../assets/babybelle/gallery-0.png',
    //     '../../assets/babybelle/text-1.png',
    //     '../../assets/babybelle/gallery-1.png',
    //     '../../assets/babybelle/text-2.png',
    //     '../../assets/babybelle/gallery-2.png',
    //     '../../assets/babybelle/text-3.png',
    //     '../../assets/babybelle/gallery-3a.png',
    //     '../../assets/babybelle/gallery-3.png',
    //     '../../assets/babybelle/text-4.png',
    //     '../../assets/babybelle/gallery-4.png',
    //     '../../assets/babybelle/text-5.png',
    //     '../../assets/babybelle/gallery-5.png',
    //     '../../assets/babybelle/text-6.png',
    //     '../../assets/babybelle/gallery-6a.png',
    //     '../../assets/babybelle/gallery-6.png',
    //     '../../assets/babybelle/text-7.png',
    //     '../../assets/babybelle/gallery-7.png',
    //   ],
    //   gallery: [
    //     '../../assets/babybelle/gallery-0.png',
    //     '../../assets/babybelle/gallery-1.png',
    //     '../../assets/babybelle/gallery-2.png',
    //     '../../assets/babybelle/gallery-3a.png',
    //     '../../assets/babybelle/gallery-3.png',
    //     '../../assets/babybelle/gallery-4.png',
    //     '../../assets/babybelle/gallery-5.png',
    //     '../../assets/babybelle/gallery-6a.png',
    //     '../../assets/babybelle/gallery-6.png',
    //     '../../assets/babybelle/gallery-7.png',
    //   ]
    // },
    // francine: {
    //   text: [
    //     '../../assets/francine/gallery-0.png',
    //     '../../assets/francine/text-1.png',
    //     '../../assets/francine/gallery-1.png',
    //     '../../assets/francine/text-2.png',
    //     '../../assets/francine/gallery-2a.png',
    //     '../../assets/francine/gallery-2.png',
    //     '../../assets/francine/text-3.png',
    //     '../../assets/francine/gallery-3b.png',
    //     '../../assets/francine/gallery-3a.png',
    //     '../../assets/francine/gallery-3.png',
    //     '../../assets/francine/text-4.png',
    //   ],
    //   gallery: [
    //     '../../assets/francine/gallery-0.png',
    //     '../../assets/francine/gallery-1.png',
    //     '../../assets/francine/gallery-2a.png',
    //     '../../assets/francine/gallery-2.png',
    //     '../../assets/francine/gallery-3b.png',
    //     '../../assets/francine/gallery-3a.png',
    //     '../../assets/francine/gallery-3.png',
    //   ]
    // },
    // amelia: {
    //   text: [
    //     '../../assets/amelia/gallery-0.png',
    //     '../../assets/amelia/text-1.png',
    //     '../../assets/amelia/gallery-1.png',
    //     '../../assets/amelia/text-2.png',
    //     '../../assets/amelia/gallery-2.png',
    //     '../../assets/amelia/text-3.png',
    //     '../../assets/amelia/gallery-3a.png',
    //     '../../assets/amelia/gallery-3.png',
    //     '../../assets/amelia/text-4.png',
    //     '../../assets/amelia/gallery-4.png',
    //     '../../assets/amelia/text-5.png',
    //     '../../assets/amelia/gallery-5a.png',
    //     '../../assets/amelia/gallery-5.png',
    //     '../../assets/amelia/text-6.png',
    //     '../../assets/amelia/gallery-6.png',
    //     '../../assets/amelia/text-7.png',
    //     '../../assets/amelia/gallery-7.png',
    //   ],
    //   gallery: [
    //     '../../assets/amelia/gallery-0.png',
    //     '../../assets/amelia/gallery-1.png',
    //     '../../assets/amelia/gallery-2.png',
    //     '../../assets/amelia/gallery-3a.png',
    //     '../../assets/amelia/gallery-3.png',
    //     '../../assets/amelia/gallery-4.png',
    //     '../../assets/amelia/gallery-5a.png',
    //     '../../assets/amelia/gallery-5.png',
    //     '../../assets/amelia/gallery-6.png',
    //     '../../assets/amelia/gallery-7.png',
    //   ]
    // },
    // darkone: {
    //   text: [
    //     '../../assets/darkone/text-1.png',
    //     '../../assets/darkone/gallery-1.png',
    //     '../../assets/darkone/text-2.png',
    //     '../../assets/darkone/gallery-2a.png',
    //     '../../assets/darkone/gallery-2.png',
    //     '../../assets/darkone/text-3.png',
    //     '../../assets/darkone/gallery-3a.png',
    //     '../../assets/darkone/gallery-3.png',
    //     '../../assets/darkone/text-4.png',
    //     '../../assets/darkone/gallery-4.png',
    //     '../../assets/darkone/gallery-5.png',
    //   ],
    //   gallery: [
    //     '../../assets/darkone/gallery-1.png',
    //     '../../assets/darkone/gallery-2a.png',
    //     '../../assets/darkone/gallery-2.png',
    //     '../../assets/darkone/gallery-3a.png',
    //     '../../assets/darkone/gallery-3.png',
    //     '../../assets/darkone/gallery-4.png',
    //     '../../assets/darkone/gallery-5.png',
    //   ]
    // },
    // qpiddy: {
    //   text: [
    //     '../../assets/qpiddy/gallery-0.png',
    //     '../../assets/qpiddy/text-1.png',
    //     '../../assets/qpiddy/gallery-1.png',
    //     '../../assets/qpiddy/text-2.png',
    //     '../../assets/qpiddy/gallery-2a.png',
    //     '../../assets/qpiddy/gallery-2.png',
    //     '../../assets/qpiddy/text-3.png',
    //     '../../assets/qpiddy/gallery-3a.png',
    //     '../../assets/qpiddy/gallery-3.png',
    //     '../../assets/qpiddy/text-4.png',
    //   ],
    //   gallery: [
    //     '../../assets/qpiddy/gallery-0.png',
    //     '../../assets/qpiddy/gallery-1.png',
    //     '../../assets/qpiddy/gallery-2a.png',
    //     '../../assets/qpiddy/gallery-2.png',
    //     '../../assets/qpiddy/gallery-3a.png',
    //     '../../assets/qpiddy/gallery-3.png',
    //   ]
    // },
    // quill: {
    //   text: [
    //     '../../assets/quill/gallery-0.png',
    //     '../../assets/quill/text-1.png',
    //     '../../assets/quill/gallery-1.png',
    //     '../../assets/quill/text-2.png',
    //     '../../assets/quill/gallery-2a.png',
    //     '../../assets/quill/gallery-2.png',
    //     '../../assets/quill/text-3.png',
    //     '../../assets/quill/gallery-3a.png',
    //     '../../assets/quill/gallery-3.png',
    //     '../../assets/quill/text-4.png',
    //   ],
    //   gallery: [
    //     '../../assets/quill/gallery-0.png',
    //     '../../assets/quill/gallery-1.png',
    //     '../../assets/quill/gallery-2a.png',
    //     '../../assets/quill/gallery-2.png',
    //     '../../assets/quill/gallery-3a.png',
    //     '../../assets/quill/gallery-3.png',
    //   ]
    // },
    // elle: {
    //   text: [
    //     '../../assets/elle/gallery-0.png',
    //     '../../assets/elle/text-1.png',
    //     '../../assets/elle/gallery-1.png',
    //     '../../assets/elle/text-2.png',
    //     '../../assets/elle/gallery-2a.png',
    //     '../../assets/elle/gallery-2.png',
    //     '../../assets/elle/text-3.png',
    //     '../../assets/elle/gallery-3a.png',
    //     '../../assets/elle/gallery-3.png',
    //     '../../assets/elle/text-4.png',
    //   ],
    //   gallery: [
    //     '../../assets/elle/gallery-0.png',
    //     '../../assets/elle/gallery-1.png',
    //     '../../assets/elle/gallery-2a.png',
    //     '../../assets/elle/gallery-2.png',
    //     '../../assets/elle/gallery-3a.png',
    //     '../../assets/elle/gallery-3.png',
    //   ]
    // },
    // iro: {
    //   text: [
    //     '../../assets/iro/gallery-0.png',
    //     '../../assets/iro/text-1.png',
    //     '../../assets/iro/gallery-1.png',
    //     '../../assets/iro/text-2.png',
    //     '../../assets/iro/gallery-2a.png',
    //     '../../assets/iro/gallery-2.png',
    //     '../../assets/iro/text-3.png',
    //     '../../assets/iro/gallery-3a.png',
    //     '../../assets/iro/gallery-3.png',
    //     '../../assets/iro/text-4.png',
    //   ],
    //   gallery: [
    //     '../../assets/iro/gallery-0.png',
    //     '../../assets/iro/gallery-1.png',
    //     '../../assets/iro/gallery-2a.png',
    //     '../../assets/iro/gallery-2.png',
    //     '../../assets/iro/gallery-3a.png',
    //     '../../assets/iro/gallery-3.png',
    //   ]
    // },
    // nina: {
    //   text: [
    //     '../../assets/nina/gallery-0.png',
    //     '../../assets/nina/text-1.png',
    //     '../../assets/nina/gallery-1.png',
    //     '../../assets/nina/text-2.png',
    //     '../../assets/nina/gallery-2a.png',
    //     '../../assets/nina/gallery-2.png',
    //     '../../assets/nina/text-3.png',
    //     '../../assets/nina/gallery-3a.png',
    //     '../../assets/nina/gallery-3.png',
    //     '../../assets/nina/text-4.png',
    //     '../../assets/nina/gallery-4a.png',
    //     '../../assets/nina/gallery-5.png',
    //   ],
    //   gallery: [
    //     '../../assets/nina/gallery-0.png',
    //     '../../assets/nina/gallery-1.png',
    //     '../../assets/nina/gallery-2a.png',
    //     '../../assets/nina/gallery-2.png',
    //     '../../assets/nina/gallery-3a.png',
    //     '../../assets/nina/gallery-3.png',
    //     '../../assets/nina/gallery-4a.png',
    //     '../../assets/nina/gallery-5.png',
    //   ]
    // },
    // karma: {
    //   text: [
    //     '../../assets/karma/gallery-0.png',
    //     '../../assets/karma/text-1.png',
    //     '../../assets/karma/gallery-1.png',
    //     '../../assets/karma/text-2.png',
    //     '../../assets/karma/gallery-2a.png',
    //     '../../assets/karma/gallery-2.png',
    //     '../../assets/karma/text-3.png',
    //     '../../assets/karma/gallery-3.png',
    //     '../../assets/karma/text-4.png',
    //     '../../assets/karma/gallery-4.png',
    //     '../../assets/karma/gallery-5.png',
    //     '../../assets/karma/gallery-6.png',
    //     '../../assets/karma/gallery-7.png',
    //     '../../assets/karma/gallery-8.png',
    //     '../../assets/karma/gallery-9.png',
    //   ],
    //   gallery: [
    //     '../../assets/karma/gallery-0.png',
    //     '../../assets/karma/gallery-1.png',
    //     '../../assets/karma/gallery-2a.png',
    //     '../../assets/karma/gallery-2.png',
    //     '../../assets/karma/gallery-3.png',
    //     '../../assets/karma/gallery-4.png',
    //     '../../assets/karma/gallery-5.png',
    //     '../../assets/karma/gallery-6.png',
    //     '../../assets/karma/gallery-7.png',
    //     '../../assets/karma/gallery-8.png',
    //     '../../assets/karma/gallery-9.png',
    //   ]
    // },
    // catara: {
    //   text: [
    //     '../../assets/catara/gallery-0.png',
    //     '../../assets/catara/text-1.png',
    //     '../../assets/catara/gallery-1.png',
    //     '../../assets/catara/text-2.png',
    //     '../../assets/catara/gallery-2a.png',
    //     '../../assets/catara/gallery-2.png',
    //     '../../assets/catara/text-3.png',
    //     '../../assets/catara/gallery-3a.png',
    //     '../../assets/catara/gallery-3.png',
    //     '../../assets/catara/text-4.png',
    //   ],
    //   gallery: [
    //     '../../assets/catara/gallery-0.png',
    //     '../../assets/catara/gallery-1.png',
    //     '../../assets/catara/gallery-2a.png',
    //     '../../assets/catara/gallery-2.png',
    //     '../../assets/catara/gallery-3a.png',
    //     '../../assets/catara/gallery-3.png',
    //   ]
    // },
    // suzu: {
    //   text: [
    //     '../../assets/suzu/gallery-0.png',
    //     '../../assets/suzu/text-1.png',
    //     '../../assets/suzu/gallery-1.png',
    //     '../../assets/suzu/text-2.png',
    //     '../../assets/suzu/gallery-2a.png',
    //     '../../assets/suzu/gallery-2.png',
    //     '../../assets/suzu/text-3.png',
    //     '../../assets/suzu/gallery-3.png',
    //     '../../assets/suzu/text-4.png',
    //     '../../assets/suzu/gallery-4.png',
    //   ],
    //   gallery: [
    //     '../../assets/suzu/gallery-0.png',
    //     '../../assets/suzu/gallery-1.png',
    //     '../../assets/suzu/gallery-2a.png',
    //     '../../assets/suzu/gallery-2.png',
    //     '../../assets/suzu/gallery-3.png',
    //     '../../assets/suzu/gallery-4.png',
    //   ]
    // },
    // mallory: {
    //   text: [
    //     '../../assets/mallory/gallery-0.png',
    //     '../../assets/mallory/text-1.png',
    //     '../../assets/mallory/gallery-1.png',
    //     '../../assets/mallory/text-2.png',
    //     '../../assets/mallory/gallery-2a.png',
    //     '../../assets/mallory/gallery-2.png',
    //     '../../assets/mallory/text-3.png',
    //     '../../assets/mallory/gallery-3a.png',
    //     '../../assets/mallory/gallery-3.png',
    //     '../../assets/mallory/text-4.png',
    //   ],
    //   gallery: [
    //     '../../assets/mallory/gallery-0.png',
    //     '../../assets/mallory/gallery-1.png',
    //     '../../assets/mallory/gallery-2a.png',
    //     '../../assets/mallory/gallery-2.png',
    //     '../../assets/mallory/gallery-3a.png',
    //     '../../assets/mallory/gallery-3.png',
    //   ]
    // },
    // brie: {
    //   text: [
    //     '../../assets/brie/gallery-0.png',
    //     '../../assets/brie/text-1.png',
    //     '../../assets/brie/gallery-1.png',
    //     '../../assets/brie/text-2.png',
    //     '../../assets/brie/gallery-2.png',
    //     '../../assets/brie/text-3.png',
    //     '../../assets/brie/gallery-3.png',
    //     '../../assets/brie/text-4.png',
    //     '../../assets/brie/gallery-4.png',
    //     '../../assets/brie/text-5.png',
    //     '../../assets/brie/gallery-5a.png',
    //     '../../assets/brie/gallery-5.png',
    //     '../../assets/brie/text-6.png',
    //     '../../assets/brie/gallery-6.png',
    //     '../../assets/brie/text-7.png',
    //     '../../assets/brie/gallery-7.png',
    //   ],
    //   gallery: [
    //     '../../assets/brie/gallery-0.png',
    //     '../../assets/brie/gallery-1.png',
    //     '../../assets/brie/gallery-2.png',
    //     '../../assets/brie/gallery-3.png',
    //     '../../assets/brie/gallery-4.png',
    //     '../../assets/brie/gallery-5a.png',
    //     '../../assets/brie/gallery-5.png',
    //     '../../assets/brie/gallery-6.png',
    //     '../../assets/brie/gallery-7.png',
    //   ]
    // },
    // audrey: {
    //   text: [
    //     '../../assets/_hp/audrey/gallery-0.jpg',
    //     '../../assets/_hp/audrey/text-1.png',
    //     '../../assets/_hp/audrey/gallery-1.jpg',
    //     '../../assets/_hp/audrey/text-2.png',
    //     '../../assets/_hp/audrey/gallery-2.jpg',
    //     '../../assets/_hp/audrey/text-3.png',
    //     '../../assets/_hp/audrey/gallery-3.jpg',
    //     '../../assets/_hp/audrey/gallery-4.jpg',
    //     '../../assets/_hp/audrey/gallery-5.jpg',
    //   ],
    //   gallery: [
    //     '../../assets/_hp/audrey/gallery-0.jpg',
    //     '../../assets/_hp/audrey/gallery-1.jpg',
    //     '../../assets/_hp/audrey/gallery-2.jpg',
    //     '../../assets/_hp/audrey/gallery-3.jpg',
    //     '../../assets/_hp/audrey/gallery-4.jpg',
    //     '../../assets/_hp/audrey/gallery-5.jpg',
    //   ]
    // },
    // nikki: {
    //   text: [
    //     '../../assets/_hp/audrey/gallery-0.jpg',
    //     '../../assets/_hp/nikki/text-1.png',
    //     '../../assets/_hp/nikki/gallery-1.jpg',
    //     '../../assets/_hp/nikki/text-2.png',
    //     '../../assets/_hp/nikki/gallery-2.jpg',
    //     '../../assets/_hp/nikki/text-3.png',
    //     '../../assets/_hp/nikki/gallery-3.jpg',
    //     '../../assets/_hp/nikki/gallery-4.jpg',
    //     '../../assets/_hp/nikki/gallery-5.jpg',
    //     '../../assets/_hp/nikki/gallery-6.jpg',
    //     '../../assets/_hp/nikki/gallery-7.jpg',
    //   ],
    //   gallery: [
    //     '../../assets/_hp/nikki/gallery-0.jpg',
    //     '../../assets/_hp/nikki/gallery-1.jpg',
    //     '../../assets/_hp/nikki/gallery-2.jpg',
    //     '../../assets/_hp/nikki/gallery-3.jpg',
    //     '../../assets/_hp/nikki/gallery-4.jpg',
    //     '../../assets/_hp/nikki/gallery-5.jpg',
    //     '../../assets/_hp/nikki/gallery-6.jpg',
    //     '../../assets/_hp/nikki/gallery-7.jpg',
    //   ]
    // },
    // tiffany: {
    //   text: [
    //     '../../assets/_hp/tiffany/gallery-0.jpg',
    //     '../../assets/_hp/tiffany/text-1.png',
    //     '../../assets/_hp/tiffany/gallery-1.jpg',
    //     '../../assets/_hp/tiffany/text-2.png',
    //     '../../assets/_hp/tiffany/gallery-2.jpg',
    //     '../../assets/_hp/tiffany/text-3.png',
    //     '../../assets/_hp/tiffany/gallery-3.jpg',
    //     '../../assets/_hp/tiffany/gallery-4.jpg',
    //     '../../assets/_hp/tiffany/gallery-5.jpg',
    //     '../../assets/_hp/tiffany/gallery-6.jpg',
    //     '../../assets/_hp/tiffany/gallery-7.jpg',
    //   ],
    //   gallery: [
    //     '../../assets/_hp/tiffany/gallery-0.jpg',
    //     '../../assets/_hp/tiffany/gallery-1.jpg',
    //     '../../assets/_hp/tiffany/gallery-2.jpg',
    //     '../../assets/_hp/tiffany/gallery-3.jpg',
    //     '../../assets/_hp/tiffany/gallery-4.jpg',
    //     '../../assets/_hp/tiffany/gallery-5.jpg',
    //     '../../assets/_hp/tiffany/gallery-6.jpg',
    //     '../../assets/_hp/tiffany/gallery-7.jpg',
    //   ]
    // },
    // aiko: {
    //   text: [
    //     '../../assets/_hp/aiko/gallery-0.jpg',
    //     '../../assets/_hp/aiko/text-1.png',
    //     '../../assets/_hp/aiko/gallery-1.jpg',
    //     '../../assets/_hp/aiko/text-2.png',
    //     '../../assets/_hp/aiko/gallery-2.jpg',
    //     '../../assets/_hp/aiko/text-3.png',
    //     '../../assets/_hp/aiko/gallery-3.jpg',
    //     '../../assets/_hp/aiko/gallery-4.jpg',
    //     '../../assets/_hp/aiko/gallery-5.jpg',
    //     '../../assets/_hp/aiko/gallery-6.jpg',
    //     '../../assets/_hp/aiko/gallery-7.jpg',
    //   ],
    //   gallery: [
    //     '../../assets/_hp/aiko/gallery-0.jpg',
    //     '../../assets/_hp/aiko/gallery-1.jpg',
    //     '../../assets/_hp/aiko/gallery-2.jpg',
    //     '../../assets/_hp/aiko/gallery-3.jpg',
    //     '../../assets/_hp/aiko/gallery-4.jpg',
    //     '../../assets/_hp/aiko/gallery-5.jpg',
    //     '../../assets/_hp/aiko/gallery-6.jpg',
    //     '../../assets/_hp/aiko/gallery-7.jpg',
    //   ]
    // },
    // lola: {
    //   text: [
    //     '../../assets/_hp/lola/gallery-0.jpg',
    //     '../../assets/_hp/lola/text-1.png',
    //     '../../assets/_hp/lola/gallery-1.jpg',
    //     '../../assets/_hp/lola/text-2.png',
    //     '../../assets/_hp/lola/gallery-2.jpg',
    //     '../../assets/_hp/lola/text-3.png',
    //     '../../assets/_hp/lola/gallery-3.jpg',
    //     '../../assets/_hp/lola/gallery-4.jpg',
    //     '../../assets/_hp/lola/gallery-5.jpg',
    //     '../../assets/_hp/lola/gallery-6.jpg',
    //     '../../assets/_hp/lola/gallery-7.jpg',
    //   ],
    //   gallery: [
    //     '../../assets/_hp/lola/gallery-0.jpg',
    //     '../../assets/_hp/lola/gallery-1.jpg',
    //     '../../assets/_hp/lola/gallery-2.jpg',
    //     '../../assets/_hp/lola/gallery-3.jpg',
    //     '../../assets/_hp/lola/gallery-4.jpg',
    //     '../../assets/_hp/lola/gallery-5.jpg',
    //     '../../assets/_hp/lola/gallery-6.jpg',
    //     '../../assets/_hp/lola/gallery-7.jpg',
    //   ]
    // },
    // beli: {
    //   text: [
    //     '../../assets/_hp/beli/gallery-0.jpg',
    //     '../../assets/_hp/beli/text-1.png',
    //     '../../assets/_hp/beli/gallery-1.jpg',
    //     '../../assets/_hp/beli/text-2.png',
    //     '../../assets/_hp/beli/gallery-2.jpg',
    //     '../../assets/_hp/beli/text-3.png',
    //     '../../assets/_hp/beli/gallery-3.jpg',
    //     '../../assets/_hp/beli/gallery-4.jpg',
    //     '../../assets/_hp/beli/gallery-5.jpg',
    //     '../../assets/_hp/beli/gallery-6.jpg',
    //     '../../assets/_hp/beli/gallery-7.jpg',
    //   ],
    //   gallery: [
    //     '../../assets/_hp/beli/gallery-0.jpg',
    //     '../../assets/_hp/beli/gallery-1.jpg',
    //     '../../assets/_hp/beli/gallery-2.jpg',
    //     '../../assets/_hp/beli/gallery-3.jpg',
    //     '../../assets/_hp/beli/gallery-4.jpg',
    //     '../../assets/_hp/beli/gallery-5.jpg',
    //     '../../assets/_hp/beli/gallery-6.jpg',
    //     '../../assets/_hp/beli/gallery-7.jpg',
    //   ]
    // },
    // kyanna: {
    //   text: [
    //     '../../assets/_hp/kyanna/gallery-0.jpg',
    //     '../../assets/_hp/kyanna/text-1.png',
    //     '../../assets/_hp/kyanna/gallery-1.jpg',
    //     '../../assets/_hp/kyanna/text-2.png',
    //     '../../assets/_hp/kyanna/gallery-2.jpg',
    //     '../../assets/_hp/kyanna/text-3.png',
    //     '../../assets/_hp/kyanna/gallery-3.jpg',
    //     '../../assets/_hp/kyanna/gallery-4.jpg',
    //     '../../assets/_hp/kyanna/gallery-5.jpg',
    //   ],
    //   gallery: [
    //     '../../assets/_hp/kyanna/gallery-0.jpg',
    //     '../../assets/_hp/kyanna/gallery-1.jpg',
    //     '../../assets/_hp/kyanna/gallery-2.jpg',
    //     '../../assets/_hp/kyanna/gallery-3.jpg',
    //     '../../assets/_hp/kyanna/gallery-4.jpg',
    //     '../../assets/_hp/kyanna/gallery-5.jpg',
    //   ]
    // },
    // jessie: {
    //   text: [
    //     '../../assets/_hp/jessie/gallery-0.jpg',
    //     '../../assets/_hp/jessie/text-1.png',
    //     '../../assets/_hp/jessie/gallery-1.jpg',
    //     '../../assets/_hp/jessie/text-2.png',
    //     '../../assets/_hp/jessie/gallery-2.jpg',
    //     '../../assets/_hp/jessie/text-3.png',
    //     '../../assets/_hp/jessie/gallery-3.jpg',
    //     '../../assets/_hp/jessie/gallery-4.jpg',
    //     '../../assets/_hp/jessie/gallery-5.jpg',
    //     '../../assets/_hp/jessie/gallery-6.jpg',
    //     '../../assets/_hp/jessie/gallery-7.jpg',
    //   ],
    //   gallery: [
    //     '../../assets/_hp/jessie/gallery-0.jpg',
    //     '../../assets/_hp/jessie/gallery-1.jpg',
    //     '../../assets/_hp/jessie/gallery-2.jpg',
    //     '../../assets/_hp/jessie/gallery-3.jpg',
    //     '../../assets/_hp/jessie/gallery-4.jpg',
    //     '../../assets/_hp/jessie/gallery-5.jpg',
    //     '../../assets/_hp/jessie/gallery-6.jpg',
    //     '../../assets/_hp/jessie/gallery-7.jpg',
    //   ]
    // },
    // momo: {
    //   text: [
    //     '../../assets/_hp/momo/text-1.png',
    //     '../../assets/_hp/momo/gallery-1.jpg',
    //     '../../assets/_hp/momo/text-2.png',
    //     '../../assets/_hp/momo/gallery-2.jpg',
    //     '../../assets/_hp/momo/text-3.png',
    //     '../../assets/_hp/momo/gallery-3.jpg',
    //     '../../assets/_hp/momo/gallery-4.jpg',
    //     '../../assets/_hp/momo/gallery-5.jpg',
    //     '../../assets/_hp/momo/gallery-6.jpg',
    //     '../../assets/_hp/momo/gallery-7.jpg',
    //   ],
    //   gallery: [
    //     '../../assets/_hp/momo/gallery-1.jpg',
    //     '../../assets/_hp/momo/gallery-2.jpg',
    //     '../../assets/_hp/momo/gallery-3.jpg',
    //     '../../assets/_hp/momo/gallery-4.jpg',
    //     '../../assets/_hp/momo/gallery-5.jpg',
    //     '../../assets/_hp/momo/gallery-6.jpg',
    //     '../../assets/_hp/momo/gallery-7.jpg',
    //   ]
    // },
    // kyu: {
    //   text: [
    //     '../../assets/_hp/kyu/text-1.png',
    //     '../../assets/_hp/kyu/gallery-1.jpg',
    //     '../../assets/_hp/kyu/text-2.png',
    //     '../../assets/_hp/kyu/gallery-2.jpg',
    //     '../../assets/_hp/kyu/text-3.png',
    //     '../../assets/_hp/kyu/gallery-3.jpg',
    //     '../../assets/_hp/kyu/gallery-4.jpg',
    //     '../../assets/_hp/kyu/gallery-5.jpg',
    //     '../../assets/_hp/kyu/gallery-6.jpg',
    //     '../../assets/_hp/kyu/gallery-7.jpg',
    //     '../../assets/_hp/kyu/gallery-8.jpg',
    //     '../../assets/_hp/kyu/gallery-9.jpg',
    //   ],
    //   gallery: [
    //     '../../assets/_hp/kyu/gallery-1.jpg',
    //     '../../assets/_hp/kyu/gallery-2.jpg',
    //     '../../assets/_hp/kyu/gallery-3.jpg',
    //     '../../assets/_hp/kyu/gallery-4.jpg',
    //     '../../assets/_hp/kyu/gallery-5.jpg',
    //     '../../assets/_hp/kyu/gallery-6.jpg',
    //     '../../assets/_hp/kyu/gallery-7.jpg',
    //     '../../assets/_hp/kyu/gallery-8.jpg',
    //     '../../assets/_hp/kyu/gallery-9.jpg',
    //   ]
    // },
    // celeste: {
    //   text: [
    //     '../../assets/_hp/celeste/text-1.png',
    //     '../../assets/_hp/celeste/gallery-1.jpg',
    //     '../../assets/_hp/celeste/text-2.png',
    //     '../../assets/_hp/celeste/gallery-2.jpg',
    //     '../../assets/_hp/celeste/text-3.png',
    //     '../../assets/_hp/celeste/gallery-3.jpg',
    //     '../../assets/_hp/celeste/gallery-4.jpg',
    //     '../../assets/_hp/celeste/gallery-5.jpg',
    //     '../../assets/_hp/celeste/gallery-6.jpg',
    //     '../../assets/_hp/celeste/gallery-7.jpg',
    //   ],
    //   gallery: [
    //     '../../assets/_hp/celeste/gallery-1.jpg',
    //     '../../assets/_hp/celeste/gallery-2.jpg',
    //     '../../assets/_hp/celeste/gallery-3.jpg',
    //     '../../assets/_hp/celeste/gallery-4.jpg',
    //     '../../assets/_hp/celeste/gallery-5.jpg',
    //     '../../assets/_hp/celeste/gallery-6.jpg',
    //     '../../assets/_hp/celeste/gallery-7.jpg',
    //   ]
    // },
    // venus: {
    //   text: [
    //     '../../assets/_hp/venus/text-1.png',
    //     '../../assets/_hp/venus/gallery-1.jpg',
    //     '../../assets/_hp/venus/text-2.png',
    //     '../../assets/_hp/venus/gallery-2.jpg',
    //     '../../assets/_hp/venus/text-3.png',
    //     '../../assets/_hp/venus/gallery-3.jpg',
    //     '../../assets/_hp/venus/gallery-4.jpg',
    //     '../../assets/_hp/venus/gallery-5.jpg',
    //     '../../assets/_hp/venus/gallery-6.jpg',
    //     '../../assets/_hp/venus/gallery-7.jpg',
    //   ],
    //   gallery: [
    //     '../../assets/_hp/venus/gallery-1.jpg',
    //     '../../assets/_hp/venus/gallery-2.jpg',
    //     '../../assets/_hp/venus/gallery-3.jpg',
    //     '../../assets/_hp/venus/gallery-4.jpg',
    //     '../../assets/_hp/venus/gallery-5.jpg',
    //     '../../assets/_hp/venus/gallery-6.jpg',
    //     '../../assets/_hp/venus/gallery-7.jpg',
    //   ]
    // },
    // la_mimichanenishiabindingbrand: {
    //   imgSet: true,
    //   prePath: '_la',
    //   text: [],
    //   extraZero: false,
    //   fileType: 'jpg',
    //   maxnum: 17
    // },
    // la_leila: {
    //   imgSet: true,
    //   prePath: '_la',
    //   text: [],
    //   extraZero: false,
    //   fileType: 'jpg',
    //   maxnum: 41
    // },
    // la_rae: {
    //   imgSet: true,
    //   prePath: '_la',
    //   text: [],
    //   extraZero: false,
    //   fileType: 'jpg',
    //   maxnum: 24
    // },
    // la_bikiniblondie: {
    //   imgSet: true,
    //   prePath: '_la',
    //   text: [],
    //   extraZero: false,
    //   fileType: 'jpg',
    //   maxnum: 13
    // },
    // la_anastacia: {
    //   imgSet: true,
    //   prePath: '_la',
    //   text: [],
    //   extraZero: false,
    //   fileType: 'jpg',
    //   maxnum: 56
    // },
    // la_kbass: {
    //   imgSet: true,
    //   prePath: '_la',
    //   text: [],
    //   extraZero: false,
    //   fileType: 'jpg',
    //   maxnum: 45
    // },
    // la_karen: {
    //   imgSet: true,
    //   prePath: '_la',
    //   text: [],
    //   extraZero: false,
    //   fileType: 'jpg',
    //   maxnum: 73
    // },
    // bath: {
    //   imgSet: true,
    //   prePath: '_mv',
    //   text: [],
    //   extraZero: false,
    //   fileType: 'jpg',
    //   maxnum: 60
    // },
    // brato: {
    //   imgSet: true,
    //   prePath: '_mv',
    //   text: [],
    //   extraZero: false,
    //   fileType: 'jpg',
    //   maxnum: 83
    // },
    // case: {
    //   imgSet: true,
    //   prePath: '_mv',
    //   text: [],
    //   extraZero: false,
    //   fileType: 'jpg',
    //   maxnum: 60
    // },
    // grab: {
    //   imgSet: true,
    //   prePath: '_mv',
    //   text: [],
    //   extraZero: false,
    //   fileType: 'jpg',
    //   maxnum: 63
    // },
    // hipp: {
    //   imgSet: true,
    //   prePath: '_mv',
    //   text: [],
    //   extraZero: false,
    //   fileType: 'jpg',
    //   maxnum: 68
    // },
    // quad: {
    //   imgSet: true,
    //   prePath: '_mv',
    //   text: [],
    //   extraZero: false,
    //   fileType: 'jpg',
    //   maxnum: 65
    // },
    // rose: {
    //   imgSet: true,
    //   prePath: '_mv',
    //   text: [],
    //   extraZero: false,
    //   fileType: 'jpg',
    //   maxnum: 59
    // },
    // sanmi: {
    //   imgSet: true,
    //   prePath: '_mv',
    //   text: [],
    //   extraZero: false,
    //   fileType: 'jpg',
    //   maxnum: 80
    // },
    // whip: {
    //   imgSet: true,
    //   prePath: '_mv',
    //   text: [],
    //   extraZero: false,
    //   fileType: 'jpg',
    //   maxnum: 76
    // },
    nh_maibathhousebonding: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: false,
      fileType: 'jpg',
      maxnum: 22
    },
    nh_stepsisandmomtakecare: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: false,
      fileType: 'jpg',
      maxnum: 157
    },
    nh_jealousboy: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: false,
      fileType: 'jpg',
      maxnum: 27
    },
    nh_villagecomingofage: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: false,
      fileType: 'jpg',
      maxnum: 34
    },
    nh_strangecountryside: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: true,
      fileType: 'jpg',
      maxnum: 162
    },
    nh_helpuncle: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: false,
      fileType: 'jpg',
      maxnum: 39
    },
    nh_notleaveisland: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: false,
      fileType: 'jpg',
      maxnum: 59
    },
    nh_garden: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: true,
      fileType: 'jpg',
      maxnum: 266
    },
    nh_villagecustom: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: false,
      fileType: 'jpg',
      maxnum: 29
    },
    nh_gfsmom: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: false,
      fileType: 'jpg',
      maxnum: 114
    },
    nh_sketching: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: true,
      fileType: 'jpg',
      maxnum: 28,
    },
    nh_summerbreak: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: true,
      fileType: 'jpg',
      maxnum: 201
    },
    nh_seriouspool: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: false,
      fileType: 'jpg',
      maxnum: 53
    },
    nh_mamilk: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: true,
      fileType: 'jpg',
      maxnum: 182
    },
    nh_mysister: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: false,
      fileType: 'jpg',
      maxnum: 94
    },
    nh_mymom: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: true,
      fileType: 'jpg',
      maxnum: 150
    },
    nh_ideallife: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: false,
      fileType: 'png',
      maxnum: 562,
    },
    nh_suckingvillage: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: false,
      fileType: 'jpg',
      maxnum: 95
    },
    nh_yowayowasensei: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: true,
      fileType: 'png',
      maxnum: 115
    },
    nh_hospitalized: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: false,
      fileType: 'jpg',
      maxnum: 88
    },
    nh_suddenlysister: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: false,
      fileType: 'png',
      maxnum: 282
    },
    nh_satensan: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: false,
      fileType: 'jpg',
      maxnum: 58
    },
    nh_brothel1: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: true,
      fileType: 'png',
      maxnum: 192
    },
    nh_brothel2: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: true,
      fileType: 'png',
      maxnum: 192
    },
    nh_futhotsprings: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: true,
      fileType: 'jpg',
      maxnum: 29
    },
    nh_futcommercial: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: false,
      fileType: 'jpg',
      maxnum: 28
    },
    nh_futbeachpolice: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: true,
      fileType: 'jpg',
      maxnum: 52
    },
    nh_girlsinbloom: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: true,
      fileType: 'jpg',
      maxnum: 190
    },
    nh_training: {
      imgSet: true,
      prePath: '_nh',
      text: [],
      extraZero: false,
      fileType: 'jpg',
      maxnum: 21
    }
  }

  constructor(
    private route: ActivatedRoute,
    private router: Router
  ) {
    this.route.queryParams.subscribe(params => {
      if (this.router.getCurrentNavigation()?.extras.state) {
        this.girl = this.router?.getCurrentNavigation()?.extras?.state['girl'];
        const girlObject = this.girlSets[this.girl];
        if (girlObject.imgSet) {
          for (let i = 1; i <= girlObject.maxnum; i++) {
            if (girlObject.extraZero) {
              girlObject.text.push(`../../assets/${girlObject.prePath}/${this.girl}/${i > 99 ? i : (i > 9 && i < 100) ? '0' + i : '00' + i}.${girlObject.fileType}`);
            } else {
              if (this.girl === 'nh_ideallife' && i > 323) {
                girlObject.text.push(`../../assets/${girlObject.prePath}/${this.girl}/${i > 9 ? i : '0' + i}.jpg`);
              } else if (girlObject.prePath === '_mv') {
                girlObject.text.push(`../../assets/${girlObject.prePath}/${this.girl}/${this.girl}${i > 9 ? i : '0' + i}.${girlObject.fileType}`);
              } else {
                girlObject.text.push(`../../assets/${girlObject.prePath}/${this.girl}/${i > 9 ? i : '0' + i}.${girlObject.fileType}`);
              }
            }
          }
        }
      }
    });
  }
}
